spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    #url: jdbc:h2:mem:testdb3
    #url: jdbc:h2:tcp://localhost/~/admin
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#    initialization-mode: always
#    platform: h2
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.ckuqz95whd48.ap-northeast-2.rds.amazonaws.com:3306/admin
    username: admin
    password: 62376919k

  #    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://exqress-db.ctxktr2nwban.ap-northeast-2.rds.amazonaws.com:3306/admin?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: admin
#    password: qwer1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
    sql:
    init:
      mode: always

server:
  port: 8000
  servlet:
    session:
      tracking-modes: cookie
      timeout: 900